In [1]:
import numpy as np
import pandas as pd
import time
import datetime

In [3]:
#Install the dependencies
# import quandl
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [31]:
import pandas as pd
df = pd.read_csv('Data/FB_data.csv')
df.index = df['Date']
df.head()

Date       Open       High        Low      Close  Adj Close  \
Date                                                                            
2014-12-31  2014-12-31  79.540001  79.800003  77.860001  78.019997  78.019997   
2015-01-02  2015-01-02  78.580002  78.930000  77.699997  78.449997  78.449997   
2015-01-05  2015-01-05  77.980003  79.250000  76.860001  77.190002  77.190002   
2015-01-06  2015-01-06  77.230003  77.589996  75.360001  76.150002  76.150002   
2015-01-07  2015-01-07  76.760002  77.360001  75.820000  76.150002  76.150002   

              Volume  
Date                  
2014-12-31  19935400  
2015-01-02  18177500  
2015-01-05  26452200  
2015-01-06  27399300  
2015-01-07  22045300

In [32]:
# Get the Adjusted Close Price 
df = df.drop(['Date', 'Open', 'High', 'Low', 'Close', 'Volume'], axis=1)
# Take a look at the new data 
print(df.head())

            Adj Close
Date                 
2014-12-31  78.019997
2015-01-02  78.449997
2015-01-05  77.190002
2015-01-06  76.150002
2015-01-07  76.150002


In [33]:
# A variable for predicting 'n' days out into the future
forecast_out = 30 #'n=30' days
#Create another column (the target ) shifted 'n' units up
df['Prediction'] = df['Adj Close'].shift(-forecast_out)
#print the new data set
print(df.tail())

             Adj Close  Prediction
Date                              
2019-10-09  179.850006         NaN
2019-10-10  180.029999         NaN
2019-10-11  184.190002         NaN
2019-10-14  183.279999         NaN
2019-10-15  188.889999         NaN


In [34]:
### Create the independent data set (X)  #######
# Convert the dataframe to a numpy array
X = np.array(df.drop(['Prediction'],1))

#Remove the last '30' rows
X = X[:-forecast_out]
print(X)

[[ 78.019997]
 [ 78.449997]
 [ 77.190002]
 ...
 [185.570007]
 [185.669998]
 [182.389999]]


In [35]:
### Create the dependent data set (y)  #####
# Convert the dataframe to a numpy array 
y = np.array(df['Prediction'])
# Get all of the y values except the last '30' rows
y = y[:-forecast_out]
print(y)

[ 75.739998  75.599998  76.709999 ... 184.190002 183.279999 188.889999]


In [36]:
# Split the data into 80% training and 20% testing
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [37]:
# Create and train the Support Vector Machine (Regressor) 
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1) 
svr_rbf.fit(x_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [38]:
# Set x_forecast equal to the last 30 rows of the original data set from Adj. Close column
x_forecast = np.array(df.drop(['Prediction'],1))[:]
print(x_forecast)

[[ 78.019997]
 [ 78.449997]
 [ 77.190002]
 ...
 [184.190002]
 [183.279999]
 [188.889999]]


In [39]:
# Print support vector regressor model predictions for the next '30' days
svm_prediction = svr_rbf.predict(x_forecast)
print(svm_prediction)

[ 81.98984385  81.55919902  82.17968826 ... 179.11775163 179.6633666
 190.55838534]


In [40]:
df['Prediction'] = svm_prediction

In [41]:
df

Adj Close  Prediction
Date                              
2014-12-31   78.019997   81.989844
2015-01-02   78.449997   81.559199
2015-01-05   77.190002   82.179688
2015-01-06   76.150002   80.684085
2015-01-07   76.150002   80.684085
2015-01-08   78.180000   81.821747
2015-01-09   77.739998   82.222941
2015-01-12   76.720001   81.577523
2015-01-13   76.449997   81.124305
2015-01-14   76.279999   80.857307
2015-01-15   74.050003   88.366890
2015-01-16   75.180000   81.362010
2015-01-20   76.239998   80.800420
2015-01-21   76.739998   81.610028
2015-01-22   77.650002   82.267816
2015-01-23   77.830002   82.161407
2015-01-26   77.500000   82.299939
2015-01-27   75.779999   80.452318
2015-01-28   76.239998   80.800420
2015-01-29   78.000000   82.009880
2015-01-30   75.910004   80.479729
2015-02-02   74.989998   82.058463
2015-02-03   75.400002   80.810001
2015-02-04   75.629997   80.509850
2015-02-05   75.610001   80.525389
2015-02-06   74.470001   84.996894
2015-02-09   74.440002   85.210173
2015-02-10   75.190002   81.331041
2015-02-11   76.510002   81.224694
2015-02-12   76.230003   80.786666
...                ...         ...
2019-09-04  187.139999  187.885383
2019-09-05  190.899994  182.507649
2019-09-06  187.490005  189.415407
2019-09-09  188.759995  190.912510
2019-09-10  186.169998  183.673279
2019-09-11  188.490005  191.342443
2019-09-12  187.470001  189.334165
2019-09-13  187.190002  188.114254
2019-09-16  186.220001  183.861146
2019-09-17  188.080002  191.165452
2019-09-18  188.139999  191.252253
2019-09-19  190.139999  184.748287
2019-09-20  189.929993  185.740523
2019-09-23  186.820007  186.404992
2019-09-24  181.279999  180.471401
2019-09-25  182.800003  180.596360
2019-09-26  180.110001  176.951221
2019-09-27  177.100006  175.896598
2019-09-30  178.080002  179.448904
2019-10-01  175.809998  173.737901
2019-10-02  174.600006  181.843675
2019-10-03  179.380005  177.170007
2019-10-04  180.449997  177.720894
2019-10-07  179.679993  176.763583
2019-10-08  177.750000  178.798523
2019-10-09  179.850006  176.723522
2019-10-10  180.029999  176.844534
2019-10-11  184.190002  179.117752
2019-10-14  183.279999  179.663367
2019-10-15  188.889999  190.558385

[1206 rows x 2 columns]

In [42]:
import pickle
with open('fb_model.pkl', 'wb') as f:
    pickle.dump(svr_rbf, f)